# Generated by Django 5.1.6 on 2025-02-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='anime_images/'),
        ),
        migrations.AddField(
            model_name='anime',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='anime_videos/'),
        ),
    ]
