# Generated by Django 5.1.6 on 2025-02-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_anime_image_anime_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
