# Generated by Django 5.1.6 on 2025-02-26 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20250226_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 26, 10, 7, 41, 947512, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
